#!/usr/bin/env python3
"""
rewrite-kml-labels.py — Rewrite <name> tags in the Google Earth KML so each
placemark carries its assigned Fairway label (Z2-S*, Z2-MATCH-*, Z3-S*, Z4-S*).
Also emit docs/heads/RENAME_MAP.md so Chase can verify before re-importing
to Google Earth.

Run from portfolio/fairway-ios/:
    python3 tools/rewrite-kml-labels.py

Stdlib only. Idempotent — second run produces identical output.

Inputs:
    docs/heads/sprinklers.json          (lat/lon → label, written by import-kml.py)
    docs/Sprinklers Google Earth (1).kml

Outputs:
    docs/Sprinklers Google Earth (1).kml — rewritten in place
    docs/heads/RENAME_MAP.md             — markdown table for human review

Match tolerance for (lat, lon): ±1e-7 (~1cm).
"""

import json
import sys
from pathlib import Path
from xml.etree import ElementTree as ET

SCRIPT_DIR = Path(__file__).parent
REPO_DIR = SCRIPT_DIR.parent
KML_PATH = REPO_DIR / "docs" / "Sprinklers Google Earth (1).kml"
HEADS_DIR = REPO_DIR / "docs" / "heads"
MANIFEST_PATH = HEADS_DIR / "sprinklers.json"
RENAME_MAP_PATH = HEADS_DIR / "RENAME_MAP.md"

KML_NS = "http://www.opengis.net/kml/2.2"
COORD_TOLERANCE = 1e-7


def q(ns, tag):
    return f"{{{ns}}}{tag}"


def load_label_map():
    manifest = json.loads(MANIFEST_PATH.read_text())
    entries = []
    for h in manifest["heads"]:
        if h["lat"] is None or h["lon"] is None:
            continue
        entries.append({
            "label": h["label"],
            "lat": h["lat"],
            "lon": h["lon"],
            "kml_name": h["kml_name"],
            "color": h["kml_color"],
            "zone": h["zone"],
        })
    return entries


def find_label(lat, lon, entries):
    for e in entries:
        if abs(e["lat"] - lat) <= COORD_TOLERANCE and abs(e["lon"] - lon) <= COORD_TOLERANCE:
            return e
    return None


def main():
    if not KML_PATH.exists():
        print(f"ERROR: KML not found at {KML_PATH}", file=sys.stderr)
        sys.exit(1)
    if not MANIFEST_PATH.exists():
        print(f"ERROR: manifest not found at {MANIFEST_PATH}; run import-kml.py first", file=sys.stderr)
        sys.exit(1)

    ET.register_namespace("", KML_NS)
    ET.register_namespace("gx", "http://www.google.com/kml/ext/2.2")

    entries = load_label_map()
    print(f"Loaded {len(entries)} (lat, lon → label) entries from manifest.")

    tree = ET.parse(KML_PATH)
    root = tree.getroot()

    rows = []
    rewritten = 0
    unmatched = []

    for pm in root.iter(q(KML_NS, "Placemark")):
        name_el = pm.find(q(KML_NS, "name"))
        old_name = name_el.text.strip() if name_el is not None and name_el.text else ""

        coords_el = pm.find(f".//{q(KML_NS, 'coordinates')}")
        if coords_el is None or not coords_el.text:
            continue
        parts = coords_el.text.strip().split(",")
        if len(parts) < 2:
            continue
        try:
            lon = float(parts[0])
            lat = float(parts[1])
        except ValueError:
            continue

        match = find_label(lat, lon, entries)
        if match is None:
            unmatched.append((old_name, lat, lon))
            continue

        new_label = match["label"]
        if old_name != new_label:
            if name_el is None:
                name_el = ET.SubElement(pm, q(KML_NS, "name"))
            name_el.text = new_label
            rewritten += 1

        rows.append({
            "old_name": old_name,
            "new_label": new_label,
            "lat": lat,
            "lon": lon,
            "zone": match["zone"],
            "color": match["color"],
        })

    if unmatched:
        print(f"\nWARNING: {len(unmatched)} placemark(s) had no manifest match:", file=sys.stderr)
        for n, la, lo in unmatched:
            print(f"  '{n}' lat={la:.7f} lon={lo:.7f}", file=sys.stderr)

    tree.write(KML_PATH, xml_declaration=True, encoding="UTF-8")
    print(f"\n{rewritten} placemark <name> tag(s) rewritten (of {len(rows)} matched).")
    print(f"KML written → {KML_PATH}")

    rows.sort(key=lambda r: (r["zone"], r["new_label"]))
    lines = [
        "# Sprinkler KML Rename Map",
        "",
        f"Generated by `tools/rewrite-kml-labels.py`. {len(rows)} placemarks.",
        "",
        "| old_name | new_label | lat | lon | zone | color |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for r in rows:
        lines.append(
            f"| `{r['old_name']}` | **{r['new_label']}** | {r['lat']:.7f} | {r['lon']:.7f} | Z{r['zone']} | `{r['color']}` |"
        )
    lines.append("")
    RENAME_MAP_PATH.write_text("\n".join(lines))
    print(f"RENAME_MAP written → {RENAME_MAP_PATH}")


if __name__ == "__main__":
    main()
