// Taxonomy v9+ seeds: Skills & guides, Learning expansion, Sales Tools (comprehensive).

export const TAXONOMY_SEED = [
  // --- Skills & guides (396–397) ---
  {
    id: 396,
    title: "Cursor Skills — index",
    url: "https://github.com/iamchasewhittaker/apps/blob/main/chase/docs/guides/CURSOR_SKILLS_INDEX.md",
    category: "Skills & guides",
    folderId: "f_my_projects_skills",
    description: "Canonical list of your Cursor skills: paths, when to use, maintenance notes",
    tags: ["skills", "cursor", "docs"],
  },
  {
    id: 397,
    title: "Portfolio docs — by app",
    url: "https://github.com/iamchasewhittaker/apps/blob/main/chase/docs/guides/PORTFOLIO_APP_DOCUMENTATION_MAP.md",
    category: "Skills & guides",
    folderId: "f_my_projects_skills",
    description: "What each app’s CLAUDE.md, HANDOFF, ROADMAP, README, etc. is for — organized by app",
    tags: ["skills", "docs", "portfolio"],
  },

  // --- Learning expansion: video, courses, metacognition (398–412) ---
  { id: 398, title: "freeCodeCamp (YouTube)", url: "https://www.youtube.com/@freecodecamp", category: "Learning", folderId: "f_learning", description: "Full courses: web, Python, CS, data — long-form video learning", tags: ["learning", "video"] },
  { id: 399, title: "3Blue1Brown", url: "https://www.youtube.com/@3blue1brown", category: "Learning", folderId: "f_learning", description: "Visual intuition for linear algebra, calculus, and neural networks", tags: ["learning", "video", "math"] },
  { id: 400, title: "Fireship", url: "https://www.youtube.com/@Fireship", category: "Learning", folderId: "f_learning", description: "100-second explainers on frameworks, languages, and trends", tags: ["learning", "video"] },
  { id: 401, title: "CS50 on YouTube", url: "https://www.youtube.com/cs50", category: "Learning", folderId: "f_learning", description: "Harvard’s intro CS — C, Python, web, SQL, and computer science thinking", tags: ["learning", "video", "cs"] },
  { id: 402, title: "Google for Developers — YouTube", url: "https://www.youtube.com/googledevelopers", category: "Learning", folderId: "f_learning", description: "Android, web, Cloud, and AI talks from Google", tags: ["learning", "video"] },
  { id: 403, title: "Chrome for Developers", url: "https://developer.chrome.com", category: "Learning", folderId: "f_learning", description: "Web platform, DevTools, extensions, and performance deep dives", tags: ["learning", "web"] },
  { id: 404, title: "Coursera", url: "https://www.coursera.org", category: "Learning", folderId: "f_learning", description: "University-backed courses and specializations with certificates", tags: ["learning", "course"] },
  { id: 405, title: "edX", url: "https://www.edx.org", category: "Learning", folderId: "f_learning", description: "MIT, Harvard, and partner courses — audit free or verify", tags: ["learning", "course"] },
  { id: 406, title: "Exercism", url: "https://exercism.org", category: "Learning", folderId: "f_learning", description: "Mentored practice in 60+ languages with free tracks", tags: ["learning", "practice"] },
  { id: 407, title: "The Odin Project", url: "https://www.theodinproject.com", category: "Learning", folderId: "f_learning", description: "Free full-stack JavaScript curriculum with projects", tags: ["learning", "web"] },
  { id: 408, title: "Obsidian", url: "https://obsidian.md", category: "Learning", folderId: "f_learning", description: "Local-first notes with graph view — good for “second brain” learning", tags: ["learning", "notes"] },
  { id: 409, title: "Readwise", url: "https://readwise.io", category: "Learning", folderId: "f_learning", description: "Resurface highlights from Kindle, articles, and tweets via spaced repetition", tags: ["learning", "retention"] },
  { id: 410, title: "Learning How to Learn (Coursera)", url: "https://www.coursera.org/learn/learning-how-to-learn", category: "Learning", folderId: "f_learning", description: "Barbara Oakley + Terrence Sejnowski on chunking, focus, and memory", tags: ["learning", "metacognition"] },
  { id: 411, title: "MIT OpenCourseWare", url: "https://ocw.mit.edu", category: "Learning", folderId: "f_learning", description: "Full MIT course materials — lecture notes, assignments, exams", tags: ["learning", "course"] },
  { id: 412, title: "Class Central", url: "https://www.classcentral.com", category: "Learning", folderId: "f_learning", description: "Search across Coursera, edX, Udacity, and more free courses", tags: ["learning", "catalog"] },

  // --- Sales Tools: glossary, CRM, blogs, video (413–448) ---
  { id: 413, title: "Gartner IT Glossary", url: "https://www.gartner.com/en/information-technology/glossary", category: "Sales Tools", folderId: "f_sales_tools", description: "Enterprise tech and business terms used in buyer conversations", tags: ["sales", "glossary"] },
  { id: 414, title: "TechTarget WhatIs glossary", url: "https://www.techtarget.com/whatis", category: "Sales Tools", folderId: "f_sales_tools", description: "Plain-English definitions for IT and security vocabulary", tags: ["sales", "glossary"] },
  { id: 415, title: "Investopedia — Sales terms", url: "https://www.investopedia.com/financial-term-taxonomy-4769734", category: "Sales Tools", folderId: "f_sales_tools", description: "Finance and business vocabulary for B2B context", tags: ["sales", "glossary"] },
  { id: 416, title: "Salesforce Trailhead", url: "https://trailhead.salesforce.com", category: "Sales Tools", folderId: "f_sales_tools", description: "Free CRM, sales cloud, and admin learning paths", tags: ["sales", "crm", "course"] },
  { id: 417, title: "HubSpot Academy", url: "https://academy.hubspot.com", category: "Sales Tools", folderId: "f_sales_tools", description: "Inbound sales, marketing, RevOps, and CRM certifications", tags: ["sales", "crm", "course"] },
  { id: 418, title: "LinkedIn Sales Navigator", url: "https://business.linkedin.com/sales-solutions/sales-navigator", category: "Sales Tools", folderId: "f_sales_tools", description: "Advanced search, lead lists, and InMail for outbound", tags: ["sales", "outbound"] },
  { id: 419, title: "Gong — Resource library", url: "https://www.gong.io/resources", category: "Sales Tools", folderId: "f_sales_tools", description: "Revenue intelligence research, call data, and sales science", tags: ["sales", "blog"] },
  { id: 420, title: "Outreach.io — Blog", url: "https://www.outreach.io/blog", category: "Sales Tools", folderId: "f_sales_tools", description: "Sales engagement, sequences, and pipeline content", tags: ["sales", "blog"] },
  { id: 421, title: "Sales Hacker", url: "https://www.saleshacker.com", category: "Sales Tools", folderId: "f_sales_tools", description: "Tactics for SDRs, AEs, and leaders — outbound and enablement", tags: ["sales", "blog"] },
  { id: 422, title: "Pavilion (community)", url: "https://www.joinpavilion.com", category: "Sales Tools", folderId: "f_sales_tools", description: "Peer groups for GTM leaders — comp, playbooks, intros", tags: ["sales", "community"] },
  { id: 423, title: "Winning by Design — SaaS sales", url: "https://www.winningbydesign.com", category: "Sales Tools", folderId: "f_sales_tools", description: "Bowtie model, recurring revenue metrics, and GTM training", tags: ["sales", "methodology"] },
  { id: 424, title: "SaaStr — Blog & videos", url: "https://www.saastr.com", category: "Sales Tools", folderId: "f_sales_tools", description: "Scaling advice from founders and VPs of Sales", tags: ["sales", "blog", "video"] },
  { id: 425, title: "JBarrows — sales training (YouTube)", url: "https://www.youtube.com/c/JBarrowsSalesTraining", category: "Sales Tools", folderId: "f_sales_tools", description: "John Barrows on prospecting, discovery, and modern selling", tags: ["sales", "video"] },
  { id: 426, title: "Art of Charm — negotiation (podcast)", url: "https://theartofcharm.com", category: "Sales Tools", folderId: "f_sales_tools", description: "Social skills, influence, and negotiation episodes", tags: ["sales", "negotiation"] },
  { id: 427, title: "Chris Voss — MasterClass trailer", url: "https://www.masterclass.com/classes/chris-voss-teaches-the-art-of-negotiation", category: "Sales Tools", folderId: "f_sales_tools", description: "FBI hostage-negotiation tactics applied to business (paid class)", tags: ["sales", "negotiation", "video"] },
  { id: 428, title: "Pipedrive Academy", url: "https://www.pipedrive.com/en/academy", category: "Sales Tools", folderId: "f_sales_tools", description: "CRM workflows, pipeline management, and sales courses", tags: ["sales", "crm"] },
  { id: 429, title: "Zoho CRM — Help", url: "https://help.zoho.com/portal/en/kb/crm", category: "Sales Tools", folderId: "f_sales_tools", description: "SMB-friendly CRM configuration and automation docs", tags: ["sales", "crm", "docs"] },
  { id: 430, title: "Close CRM — Blog", url: "https://www.close.com/blog", category: "Sales Tools", folderId: "f_sales_tools", description: "High-velocity inside sales and calling workflows", tags: ["sales", "blog"] },
  { id: 431, title: "Lemlist — Cold email blog", url: "https://www.lemlist.com/blog", category: "Sales Tools", folderId: "f_sales_tools", description: "Deliverability, personalization, and outbound sequences", tags: ["sales", "outbound"] },
  { id: 432, title: "Apollo.io — Blog", url: "https://www.apollo.io/blog", category: "Sales Tools", folderId: "f_sales_tools", description: "Prospecting data, sequencing, and GTM ops", tags: ["sales", "outbound"] },
  { id: 433, title: "ZoomInfo — Blog", url: "https://www.zoominfo.com/business/sales", category: "Sales Tools", folderId: "f_sales_tools", description: "Intent data, org charts, and enterprise prospecting", tags: ["sales", "research"] },
  { id: 434, title: "Cognism — GTM blog", url: "https://www.cognism.com/blog", category: "Sales Tools", folderId: "f_sales_tools", description: "B2B data compliance (GDPR) and outbound playbooks", tags: ["sales", "blog"] },
  { id: 435, title: "Clay — Blog", url: "https://www.clay.com/blog", category: "Sales Tools", folderId: "f_sales_tools", description: "Waterfall enrichment, outbound tables, and creative prospecting", tags: ["sales", "outbound"] },
  { id: 436, title: "Bravado — War Room", url: "https://bravado.co", category: "Sales Tools", folderId: "f_sales_tools", description: "Community for reps — comp, reviews, and deal talk", tags: ["sales", "community"] },
  { id: 437, title: "RevGenius (Slack community)", url: "https://www.revgenius.com", category: "Sales Tools", folderId: "f_sales_tools", description: "Modern sales, marketing, and CS professionals network", tags: ["sales", "community"] },
  { id: 438, title: "Challenger Inc. — Insights", url: "https://challengerinc.com/insights", category: "Sales Tools", folderId: "f_sales_tools", description: "Teach-Tailor-Take control methodology and research", tags: ["sales", "methodology"] },
  { id: 439, title: "MEDDIC / MEDDICC overview (Force Management)", url: "https://forcemanagement.com/blog/meddicc-sales-methodology", category: "Sales Tools", folderId: "f_sales_tools", description: "Enterprise qualification framework for complex deals", tags: ["sales", "methodology"] },
  { id: 440, title: "SPICED (Winning by Design)", url: "https://www.winningbydesign.com/spiced", category: "Sales Tools", folderId: "f_sales_tools", description: "Situation, Pain, Impact, Critical event, Decision — SaaS discovery", tags: ["sales", "methodology"] },
  { id: 441, title: "Pavilion — Metrics glossary", url: "https://www.joinpavilion.com/glossary", category: "Sales Tools", folderId: "f_sales_tools", description: "ARR, NRR, CAC, magic number — RevOps definitions", tags: ["sales", "glossary"] },
  { id: 442, title: "OpenView — PLG resources", url: "https://openviewpartners.com/blog", category: "Sales Tools", folderId: "f_sales_tools", description: "Product-led growth and expansion revenue content", tags: ["sales", "plg"] },
  { id: 443, title: "Bessemer — Scaling Sales", url: "https://www.bvp.com/atlas", category: "Sales Tools", folderId: "f_sales_tools", description: "VC perspective on GTM milestones and hiring", tags: ["sales", "strategy"] },
  { id: 444, title: "Seismic — Learning center", url: "https://www.seismic.com/enablement-learning", category: "Sales Tools", folderId: "f_sales_tools", description: "Sales enablement, content, and coaching platform resources", tags: ["sales", "enablement"] },
  { id: 445, title: "Highspot — Blog", url: "https://www.highspot.com/blog", category: "Sales Tools", folderId: "f_sales_tools", description: "Enablement, readiness, and buyer engagement", tags: ["sales", "enablement"] },
  { id: 446, title: "Salesforce — State of Sales (report)", url: "https://www.salesforce.com/resources/research-reports/state-of-sales", category: "Sales Tools", folderId: "f_sales_tools", description: "Annual trends on selling, AI, and revenue ops", tags: ["sales", "research"] },
  { id: 447, title: "HubSpot — State of Sales", url: "https://www.hubspot.com/state-of-sales", category: "Sales Tools", folderId: "f_sales_tools", description: "Survey data on quotas, channels, and buyer behavior", tags: ["sales", "research"] },
  { id: 448, title: "Lavender — Sales email AI", url: "https://www.lavender.ai", category: "Sales Tools", folderId: "f_sales_tools", description: "Email coaching, personalization scores, and team analytics", tags: ["sales", "ai"] },
];
